title: Bias Toolkit
baseurl: ""
url: ""

collections:
  tools:
    output: true
    permalink: /resources/:name/

defaults:
  - scope:
      path: "_tools"
    values:
      layout: "tool"

plugins:
  - jekyll-sitemap

exclude:
  - assets/js/src
  - Gemfile*
  - node_modules
  - package*.json
  - README.md
  - vendor
  - webpack.config.js
